OPENAI_API_KEY = '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'
ASSISTANT_ID = 'asst_Jn2KTP27Z3XAmQSq6KhARMfH'
[mysql]
host = "localhost"
port = 3306
database = "law"
user = "root"
password = ""